export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const POST_VIDEOGAMES = 'POST_VIDEOGAMES';
export const PUT_VIDEOGAMES = 'PUT_VIDEOGAMES';
export const DELETE_VIDEOGAMES = 'DELETE_VIDEOGAMES';
export const DETAIL_VIDEOGAME = 'DETAIL_VIDEOGAME';
export const GET_GENRES = 'GET_GENRES';
